name: Leer archivo desde Data Lake 
on:
  push: 
     branches: main

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v3
     - name: Set up Python
       uses: actions/setup-python@v3
       with:
         python-version: '3.9'
     - name: update prp
       run: pip install --upgrade pip
     - name: Install dependencies
       run: pip install -r requirements.txt
     - name: Run script
       run: |
        echo main.py
        python main.py
       

