name: Leer archivo desde Data Lake 
on:
  schedule:
    - cron:  '0 23 * * 5'
    # This runs at 23:00 UTC each friday.
    # * is a special character in YAML so you have to quote this string

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v3
     - name: Set up Python
       uses: actions/setup-python@v4
       with:
         python-version: '3.9'
     - name: Install dependencies
       run: pip install -r requirements.txt
     - name: Run script
       run: python main.py 
